
package mx.gob.imss.cit.pmc.validacionalmacenes.cuentaindividual;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.gob.imss.sisec.cuentaindividual.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSCuentaIndividualSISEC", targetNamespace = "http://cuentaIndividual.sisec.imss.gob.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSCuentaIndividualSISEC {


    /**
     * 
     * @param nss
     * @return
     *     returns mx.gob.imss.sisec.cuentaindividual.RespuestaCuentaIndividual
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCuentaIndividualSISEC", targetNamespace = "http://cuentaIndividual.sisec.imss.gob.mx/", className = "mx.gob.imss.sisec.cuentaindividual.GetCuentaIndividualSISEC")
    @ResponseWrapper(localName = "getCuentaIndividualSISECResponse", targetNamespace = "http://cuentaIndividual.sisec.imss.gob.mx/", className = "mx.gob.imss.sisec.cuentaindividual.GetCuentaIndividualSISECResponse")
    public RespuestaCuentaIndividual getCuentaIndividualSISEC(
        @WebParam(name = "nss", targetNamespace = "")
        String nss);

}
