
package mx.gob.imss.cit.pmc.validacionalmacenes.cuentaindividual;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSCuentaIndividualSISEC", targetNamespace = "http://cuentaIndividual.sisec.imss.gob.mx/", wsdlLocation = "http://11.254.13.146:7001/WSCuentaIndividualSISEC/WSCuentaIndividualSISEC?WSDL")
public class WSCuentaIndividualSISEC_Service
    extends Service
{

    private final static URL WSCUENTAINDIVIDUALSISEC_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mx.gob.imss.cit.pmc.validacionalmacenes.cuentaindividual.WSCuentaIndividualSISEC_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mx.gob.imss.cit.pmc.validacionalmacenes.cuentaindividual.WSCuentaIndividualSISEC_Service.class.getResource(".");
            url = new URL(baseUrl, "http://11.254.13.146:7001/WSCuentaIndividualSISEC/WSCuentaIndividualSISEC?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://11.254.13.146:7001/WSCuentaIndividualSISEC/WSCuentaIndividualSISEC?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSCUENTAINDIVIDUALSISEC_WSDL_LOCATION = url;
    }

    public WSCuentaIndividualSISEC_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCuentaIndividualSISEC_Service() {
        super(WSCUENTAINDIVIDUALSISEC_WSDL_LOCATION, new QName("http://cuentaIndividual.sisec.imss.gob.mx/", "WSCuentaIndividualSISEC"));
    }

    /**
     * 
     * @return
     *     returns WSCuentaIndividualSISEC
     */
    @WebEndpoint(name = "WSCuentaIndividualSISECPort")
    public WSCuentaIndividualSISEC getWSCuentaIndividualSISECPort() {
        return super.getPort(new QName("http://cuentaIndividual.sisec.imss.gob.mx/", "WSCuentaIndividualSISECPort"), WSCuentaIndividualSISEC.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCuentaIndividualSISEC
     */
    @WebEndpoint(name = "WSCuentaIndividualSISECPort")
    public WSCuentaIndividualSISEC getWSCuentaIndividualSISECPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cuentaIndividual.sisec.imss.gob.mx/", "WSCuentaIndividualSISECPort"), WSCuentaIndividualSISEC.class, features);
    }

}
