
package mx.gob.imss.sisec.cuentaindividual;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSHistoricoCentralSISEC", targetNamespace = "http://cuentaIndividual.sisec.imss.gob.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSHistoricoCentralSISEC {


    /**
     * 
     * @param nss
     * @return
     *     returns mx.gob.imss.sisec.cuentaindividual.RespuestaHistoricoCuentaIndividual
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHistoricoCentralSISEC", targetNamespace = "http://cuentaIndividual.sisec.imss.gob.mx/", className = "mx.gob.imss.sisec.cuentaindividual.GetHistoricoCentralSISEC")
    @ResponseWrapper(localName = "getHistoricoCentralSISECResponse", targetNamespace = "http://cuentaIndividual.sisec.imss.gob.mx/", className = "mx.gob.imss.sisec.cuentaindividual.GetHistoricoCentralSISECResponse")
    public RespuestaHistoricoCuentaIndividual getHistoricoCentralSISEC(
        @WebParam(name = "nss", targetNamespace = "")
        String nss);

}
