
package mx.gob.imss.sisec.cuentaindividual;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSHistoricoCentralSISEC", targetNamespace = "http://cuentaIndividual.sisec.imss.gob.mx/", wsdlLocation = "http://11.254.13.146:7001/WSHistoricoCentralSISEC/WSHistoricoCentralSISEC?WSDL")
public class WSHistoricoCentralSISEC_Service
    extends Service
{

    private final static URL WSHISTORICOCENTRALSISEC_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mx.gob.imss.sisec.cuentaindividual.WSHistoricoCentralSISEC_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mx.gob.imss.sisec.cuentaindividual.WSHistoricoCentralSISEC_Service.class.getResource(".");
            url = new URL(baseUrl, "http://11.254.13.146:7001/WSHistoricoCentralSISEC/WSHistoricoCentralSISEC?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://11.254.13.146:7001/WSHistoricoCentralSISEC/WSHistoricoCentralSISEC?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSHISTORICOCENTRALSISEC_WSDL_LOCATION = url;
    }

    public WSHistoricoCentralSISEC_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSHistoricoCentralSISEC_Service() {
        super(WSHISTORICOCENTRALSISEC_WSDL_LOCATION, new QName("http://cuentaIndividual.sisec.imss.gob.mx/", "WSHistoricoCentralSISEC"));
    }

    /**
     * 
     * @return
     *     returns WSHistoricoCentralSISEC
     */
    @WebEndpoint(name = "WSHistoricoCentralSISECPort")
    public WSHistoricoCentralSISEC getWSHistoricoCentralSISECPort() {
        return super.getPort(new QName("http://cuentaIndividual.sisec.imss.gob.mx/", "WSHistoricoCentralSISECPort"), WSHistoricoCentralSISEC.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSHistoricoCentralSISEC
     */
    @WebEndpoint(name = "WSHistoricoCentralSISECPort")
    public WSHistoricoCentralSISEC getWSHistoricoCentralSISECPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cuentaIndividual.sisec.imss.gob.mx/", "WSHistoricoCentralSISECPort"), WSHistoricoCentralSISEC.class, features);
    }

}
